---

name: Maven verify

on:
  push:
    branches: [ main,release ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # for Codecov
          fetch-depth: 2
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25-ea'
          distribution: 'temurin'
          cache: maven
      - name: Maven verify
        run: ./mvnw -B verify javadoc:jar source:jar site
      - uses: codecov/test-results-action@v1
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
